### PR TITLE
ASI-24

### PR DESCRIPTION
**Pull request by ehanson8**
#### What does this PR do?
* Format output of populate_fund_data function as an OrderedDict
* Add corresponding unit test
* Add invoice fixture where the external IDs of the funds are not appearing in numerical order

#### Helpful background context
I left the `fund_data` assert in place from the other `populate_fund_data` test to ensure the data was the same overall since a dict seems to reconcile as equal to an Ordered Dict even though they would iterate differently depending on when the keys were added to the dict. To test the iteration, added 3 `next` asserts to mimic how this would be iterated through when it's passed to the `generate_report` function. Let me know if there's a better way to do this.

#### What are the relevant tickets?
* https://mitlibraries.atlassian.net/browse/ASI-24

#### Requires Database Migrations?
NO

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Review by adamshire123 — COMMENTED** [review]
Are we supposed to be sorting by fund code e.g. ABC DEF GHI or by external ID?

**Comment by ehanson8** [comment]
My assumption was `external_id` based on what shows up in the final report and the reference to "numerical" in the [ticket ](https://mitlibraries.atlassian.net/browse/ASI-24)

**Comment by hakbailey** [comment]
> My assumption was `external_id` based on what shows up in the final report and the reference to "numerical" in the [ticket ](https://mitlibraries.atlassian.net/browse/ASI-24)

Hmmm. The ticket and my notes say fund code. @ehanson8 can you double check with Martina in the ticket so we have it documented?

**Comment by ehanson8** [comment]
Done, I'll update everyone with her reply

**Comment by ehanson8** [comment]
Martina confirmed it is the external ID, https://mitlibraries.atlassian.net/browse/ASI-24

**Review by hakbailey — APPROVED** [review]

**Pull request merged**
